moving image tag to app repo

diff --git a/deploy/docker/Jenkinsfile b/deploy/docker/Jenkinsfile
--- a/deploy/docker/Jenkinsfile
+++ b/deploy/docker/Jenkinsfile
@@ -2,7 +2,7 @@ pipeline {
     agent any
     environment {
         AWS_ACCOUNT_ID = "${ params.Account }"
-        IMAGE_TAG = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
+        // IMAGE_TAG = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
         REPOSITORY = "${ params.Repository }"
         BRANCH = "${ params.Branch }"
     }
@@ -14,19 +14,40 @@ pipeline {
                     sh """
                         rm -r application_files && mkdir application_files
                         git clone -b ${BRANCH} ${REPOSITORY} application_files
-                        if [ ! -d "application_files/deploy" ]; then
-                            echo "Please have the deploy directory in the root of the application with a config.yaml file present"
-                            exit 1
-                        fi
+                    """
+                    
+                    IMAGE_TAG = sh(script: 'git -C application_files rev-parse --short HEAD', returnStdout: true).trim()
+                    echo "Image Tag: ${IMAGE_TAG}"
 
+                    if (fileExists('application_files/deploy') == false) {
+                        echo "Please have the deploy directory in the root of the application with a config.yaml file present"
+                        error("Deploy directory is missing")
+                    }
+
+                    sh """
                         ls -la application_files
                         sudo cp -r application_files/.[!.]* application_files/* .
                         sudo cp -r application_files/deploy/docker/. deploy/docker/
                         sudo cp -r application_files/deploy/scripts/. deploy/scripts/
                         sudo chown -R ec2-user:ec2-user .
                         ls -lah
-
                     """
+                    // sh """
+                    //     rm -r application_files && mkdir application_files
+                    //     git clone -b ${BRANCH} ${REPOSITORY} application_files
+                    //     if [ ! -d "application_files/deploy" ]; then
+                    //         echo "Please have the deploy directory in the root of the application with a config.yaml file present"
+                    //         exit 1
+                    //     fi
+
+                    //     ls -la application_files
+                    //     sudo cp -r application_files/.[!.]* application_files/* .
+                    //     sudo cp -r application_files/deploy/docker/. deploy/docker/
+                    //     sudo cp -r application_files/deploy/scripts/. deploy/scripts/
+                    //     sudo chown -R ec2-user:ec2-user .
+                    //     ls -lah
+
+                    // """
                 }
             }
         }
